### ISSUE TITLE
Styling 

### ISSUE THREAD

**Issue by rajdip-b** [rajdip-b/myChatServer#2]
Can someone please style the README file??

**Comment by GustavoTxFreitas** [comment]
Hey, man, what's up?
I've been working on this subject, check if you like the result: #3.

**Comment by rajdip-b** [comment]
> 
> 
> Hey, man, what's up? I've been working on this subject, check if you like the result: #3.

Thanks @GustavoTxFreitas !! I really liked your work and was exactly looking for something like that. Ill be mentioning you the next time this or any other repos of mine need styling. Also, i was looking for documentation, so if you are familiar with java perhaps take a look at the code?? :D

**Comment by GustavoTxFreitas** [comment]
I am not used to javadoc, but I intend to deepen my studies in the language soon.
You can count on me for any repo, see you! :smile:

**Comment by rajdip-b** [comment]
@GustavoTxFreitas Will keep that pinned!
